// Copyright (c) Pixeval.CoreApi.
// Licensed under the GPL v3 License.

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Mako.Model;
using Mako.Net.Request;
using Mako.Net.Response;
using Misaki;

namespace Mako;

[JsonSerializable(typeof(AutoCompletionResponse))]
[JsonSerializable(typeof(PixivBookmarkTagResponse))]
[JsonSerializable(typeof(PixivCommentResponse))]
[JsonSerializable(typeof(PixivIllustrationResponse))]
// [JsonSerializable(typeof(PixivNextUrlResponse<>))]
[JsonSerializable(typeof(PixivNovelResponse))]
[JsonSerializable(typeof(PixivRelatedUsersResponse))]
[JsonSerializable(typeof(PixivSingleIllustResponse))]
[JsonSerializable(typeof(PixivSingleNovelResponse))]
[JsonSerializable(typeof(PixivSingleUserResponse))]
[JsonSerializable(typeof(Profile))]
[JsonSerializable(typeof(ProfilePublicity))]
[JsonSerializable(typeof(Workspace))]
[JsonSerializable(typeof(PixivSpotlightDetailResponse))]
[JsonSerializable(typeof(SpotlightBody))]
[JsonSerializable(typeof(Entry))]
[JsonSerializable(typeof(PixivisionCategory))]
[JsonSerializable(typeof(PixivisionSubcategory))]
[JsonSerializable(typeof(PixivisionTag))]
[JsonSerializable(typeof(Illust))]
[JsonSerializable(typeof(Url))]
[JsonSerializable(typeof(RelatedArticle))]
[JsonSerializable(typeof(PixivSpotlightResponse))]
[JsonSerializable(typeof(PixivUserResponse))]
[JsonSerializable(typeof(PostCommentResponse))]
[JsonSerializable(typeof(ReverseSearchResponse))]
[JsonSerializable(typeof(ReverseSearchResponseHeader))]
[JsonSerializable(typeof(Result))]
[JsonSerializable(typeof(Data))]
[JsonSerializable(typeof(ResultHeader))]
[JsonSerializable(typeof(TrendingTagResponse))]
[JsonSerializable(typeof(UgoiraMetadataResponse))]
[JsonSerializable(typeof(UgoiraMetadata))]
[JsonSerializable(typeof(Frame))]
[JsonSerializable(typeof(ZipUrls))]
[JsonSerializable(typeof(UserSpecifiedBookmarkTagResponse))]
[JsonSerializable(typeof(UserSpecifiedBookmarkTagBody))]
[JsonSerializable(typeof(UserSpecifiedBookmarkTag))]
[JsonSerializable(typeof(WebApiBookmarksWithTagResponse))]
[JsonSerializable(typeof(WebApiBookmarksWithTagBody))]
[JsonSerializable(typeof(Work))]
[JsonSerializable(typeof(ShowAiSettingsResponse))]
[JsonSerializable(typeof(RestrictedModeSettingsResponse))]

[JsonSerializable(typeof(IArtworkInfo))]
[JsonSerializable(typeof(BookmarkTag))]
[JsonSerializable(typeof(Feed))]
[JsonSerializable(typeof(Illustration))]
[JsonSerializable(typeof(MetaSinglePage))]
[JsonSerializable(typeof(ImageUrls))]
[JsonSerializable(typeof(MangaImageUrls))]
[JsonSerializable(typeof(MetaPage))]
[JsonSerializable(typeof(Novel))]
[JsonSerializable(typeof(Series))]
[JsonSerializable(typeof(NovelContent))]
[JsonSerializable(typeof(Rating))]
[JsonSerializable(typeof(SeriesNavigation))]
[JsonSerializable(typeof(NovelNavigation))]
[JsonSerializable(typeof(NovelImage))]
[JsonSerializable(typeof(NovelImageUrls))]
[JsonSerializable(typeof(NovelIllustInfo))]
[JsonSerializable(typeof(NovelIllust))]
[JsonSerializable(typeof(NovelTag))]
[JsonSerializable(typeof(NovelIllustUrls))]
[JsonSerializable(typeof(NovelUser))]
[JsonSerializable(typeof(NovelReplaceableGlossary))]
[JsonSerializable(typeof(ProfileImageUrls))]
[JsonSerializable(typeof(Spotlight))]
[JsonSerializable(typeof(SpotlightDetail))]
[JsonSerializable(typeof(Tag))]
[JsonSerializable(typeof(TrendingTag))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserEntity))]
[JsonSerializable(typeof(Comment))]
[JsonSerializable(typeof(Stamp))]
[JsonSerializable(typeof(CommentUser))]
[JsonSerializable(typeof(TokenResponse))]
[JsonSerializable(typeof(TokenUser))]
[JsonSerializable(typeof(TokenProfileImageUrls))]

[JsonSerializable(typeof(AddIllustBookmarkRequest))]
[JsonSerializable(typeof(AddNormalIllustCommentRequest))]
[JsonSerializable(typeof(AddNormalNovelCommentRequest))]
[JsonSerializable(typeof(AddNovelBookmarkRequest))]
[JsonSerializable(typeof(AddStampIllustCommentRequest))]
[JsonSerializable(typeof(AddStampNovelCommentRequest))]
[JsonSerializable(typeof(DeleteCommentRequest))]
[JsonSerializable(typeof(FollowUserRequest))]
[JsonSerializable(typeof(RefreshSessionRequest))]
[JsonSerializable(typeof(RemoveIllustBookmarkRequest))]
[JsonSerializable(typeof(RemoveFollowUserRequest))]
[JsonSerializable(typeof(RemoveNovelBookmarkRequest))]
[JsonSerializable(typeof(ShowAiSettingsRequest))]
[JsonSerializable(typeof(RestrictedModeSettingsRequest))]
[JsonSerializable(typeof(ReverseSearchRequest))]

[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyList<Tag>))]
[JsonSerializable(typeof(IReadOnlyList<MetaPage>))]
[JsonSerializable(typeof(IReadOnlyList<NovelIllustInfo>))]
[JsonSerializable(typeof(IReadOnlyList<NovelImage>))]
[JsonSerializable(typeof(IReadOnlyList<NovelReplaceableGlossary>))]
[JsonSerializable(typeof(IReadOnlyList<long>))]
[JsonSerializable(typeof(IReadOnlyList<NovelTag>))]
[JsonSerializable(typeof(IReadOnlyList<BookmarkTag>))]
[JsonSerializable(typeof(IReadOnlyList<Comment>))]
[JsonSerializable(typeof(IReadOnlyList<Illustration>))]
[JsonSerializable(typeof(IReadOnlyList<Novel>))]
[JsonSerializable(typeof(IReadOnlyList<User>))]
[JsonSerializable(typeof(IReadOnlyList<SpotlightBody>))]
[JsonSerializable(typeof(IReadOnlyList<PixivisionTag>))]
[JsonSerializable(typeof(IReadOnlyList<Illust>))]
[JsonSerializable(typeof(IReadOnlyList<RelatedArticle>))]
[JsonSerializable(typeof(IReadOnlyList<Spotlight>))]
[JsonSerializable(typeof(IReadOnlyList<Result>))]
[JsonSerializable(typeof(IReadOnlyList<TrendingTag>))]
[JsonSerializable(typeof(IReadOnlyList<Frame>))]
[JsonSerializable(typeof(IReadOnlyList<UserSpecifiedBookmarkTag>))]
[JsonSerializable(typeof(IReadOnlyList<Work>))]
public partial class AppJsonSerializerContext : JsonSerializerContext;

public class SnakeCaseLowerEnumConverter<T>() : JsonStringEnumConverter<T>(JsonNamingPolicy.SnakeCaseLower) where T : struct, Enum;
